name: Deploy to Clever Cloud Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      CLEVER_SECRET: ${{secrets.CLEVER_SECRET}}
      CLEVER_TOKEN: ${{secrets.CLEVER_TOKEN}}
      CLEVER_APP_ID: ${{ vars.CLEVER_APP_ID }}
      CURRENT_BRANCH: ${{github.head_ref || github.ref_name}}
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - run: sudo npm install --global clever-tools@^4.11.0
      - run: clever version
      - run: echo "Current branch is '$CURRENT_BRANCH'"
      - run: echo "DEBUG > CLEVER_SECRET = $CLEVER_SECRET , CLEVER_TOKEN = $CLEVER_TOKEN and CLEVER_APP_ID = $CLEVER_APP_ID "
      - run: clever login --secret $CLEVER_SECRET --token $CLEVER_TOKEN
      - run: clever link $CLEVER_APP_ID
